### ISSUE TITLE
Can you make a new release?

### ISSUE THREAD

**Issue by robert-iddink** [PatrickJS/angular-uuid-secure#2]
I'd like these commits included:
https://github.com/gdi2290/angular-uuid-secure/commit/f6b944f6e7fa216b29f0d3164fbe1dc012cb6f7f
https://github.com/Arzie/angular-uuid-secure/commit/0f06b46498d0b5114981008a98e29ac1bef95310

Thanks!

**Comment by PatrickJS** [comment]
thanks, pushed as [v0.0.6](https://github.com/gdi2290/angular-uuid-secure/tree/v0.0.6)

**Comment by robert-iddink** [comment]
Thank you!
